<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Republic.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\unity\Scripts\Republic.Unity.Bridge\**\*.cs" Link="Bridge\%(RecursiveDir)%(FileName)%(Extension)" />
  </ItemGroup>
</Project>
